name: Build plain pebble page

on:
  schedule:
    - cron: "*/5 * * * *"        # every 5 minutes
  workflow_dispatch:
  push:
    branches: [ main ]           # <-- make sure this matches the branch your Pages uses

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Debug secrets presence
        run: |
          echo "NIGHTSCOUT_URL set? ${{ secrets.NIGHTSCOUT_URL != '' }}"
          echo "NIGHTSCOUT_TOKEN set? ${{ secrets.NIGHTSCOUT_TOKEN != '' }}"
          echo "NIGHTSCOUT_TZ set? ${{ secrets.NIGHTSCOUT_TZ != '' }}"
          echo "FORCE_MMOL set? ${{ secrets.FORCE_MMOL != '' }}"

      - name: Install dependencies and create lockfile
        run: npm install --no-audit --no-fund

      - name: Build index.html from Nightscout /pebble
        env:
          NIGHTSCOUT_URL: ${{ secrets.NIGHTSCOUT_URL }}
          NIGHTSCOUT_TOKEN: ${{ secrets.NIGHTSCOUT_TOKEN }}
          NIGHTSCOUT_TZ: ${{ secrets.NIGHTSCOUT_TZ }}
          FORCE_MMOL: ${{ secrets.FORCE_MMOL }}   # set to "true" (string) to force mmol
        run: npm run build

      # --- NEW: show exactly what changed before committing
      - name: Show changes before commit
        run: |
          echo "-------- git status --------"
          git status
          echo "-------- changed files (git diff --name-only) --------"
          git diff --name-only
          echo "-------- ls -la at repo root --------"
          ls -la
          echo "-------- list versioned files (if any) --------"
          ls -la v || true
          echo "-------------------------------------"

      # Commit lockfile, index.html, and any versioned HTML files under v/
      - name: Commit & push updated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh pebble-plain and update lockfile"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          file_pattern: |
            package-lock.json
            index.html
            v/*.html
